blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from python_blog.views import main, about
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('python_blog.urls')),
    path('about/', about, name = 'about'),
    path('users/', include('users.urls')),
    path('', main, name = 'main'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

blog/python_blog/urls.py
from django.urls import path
from python_blog.views import catalog_posts,post_detail,catalog_categories,category_detail,catalog_tags,tag_detail,post_create,post_update

app_name = 'blog'

urlpatterns = [
    path('', catalog_posts, name = 'posts'),
# Формы поста
    path('post_create/', post_create, name='post_create'),
    path('post_update/<slug:post_slug>/', post_update, name='post_update'),
# Категории
    path('categories/', catalog_categories, name = 'categories'),
    path('categories/<slug:category_slug>/', category_detail, name = 'category_detail'),
# Теги
    path('tags/', catalog_tags, name = 'tags'),
    path('tags/<slug:tag_slug>/', tag_detail, name = 'tag_detail'),
# Посты
    path('<slug:post_slug>/', post_detail, name = 'post_detail'),
]

blog/python_blog/models.py
from django.db import models
from unidecode import unidecode
from django.utils.text import slugify
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    slug = models.SlugField(unique=True, blank=True, verbose_name='URL')

    def __str__(self):
        return str(self.name)

class Tag(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    slug = models.SlugField(unique=True, blank=True, verbose_name='URL')

class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    content = models.TextField(verbose_name="Содержание", null=True)
    slug = models.SlugField(unique=True, blank=True, verbose_name="URL")
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name="posts",
        null=True,
        blank=True,
        verbose_name="Категория",
    )
    tags = models.ManyToManyField(
        Tag, related_name="posts", blank=True, verbose_name="Теги"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_date = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")
    views = models.IntegerField(default=0, verbose_name="Просмотры")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
            print(self.slug)
        super().save(*args, **kwargs)

    def str(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"post_slug": self.slug})  

blog/python_blog/forms.py
from django import forms
from django.forms import widgets

from python_blog.models import Post


class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False)
    s_from = forms.CharField(max_length=100, required=False)


class PostForm(forms.ModelForm):
    model = Post
    fields = [
        "title",
        "content",
        "category",
    ]
    tag_string = forms.CharField(max_length=200, required=False)

    class Meta:
        model = Post
        fields = ["title", "content", "category"]
        widgets = {
            "category": widgets.Select(attrs={"class": "form-control"}),
        }

blog/python_blog/views.py
from django.shortcuts import render
from django.urls import reverse
from django.core.paginator import Paginator
from django.db.models import F, Q, Count
from python_blog.forms import PostForm, SearchForm
from .blog_data import dataset
from .models import Post, Category, Tag
from django.shortcuts import redirect, get_object_or_404
from django.utils.text import slugify
from unidecode import unidecode


def main(request):
    # catalog_categories_url = reverse("blog:categories")
    # catalog_tags_url = reverse("blog:tags")

    context = {
        "title": "Главная страница",
        "text": "Текст главной страницы",
        "user_status": "moderator",
    }
    return render(request, "main.html", context=context)


def about(request):
    return render(request, "about.html")


def catalog_posts(request):

    forms = SearchForm(request.GET)
    q_obj = Q()

    if forms.is_valid():
        search = forms.cleaned_data.get("search")
        s_from = forms.cleaned_data.get("s_from")
        if s_from == "title":
            q_obj |= Q(title__icontains=search)
        elif s_from == "tags":
            q_obj |= Q(tags__name__icontains=search)
        else:
            q_obj |= Q(content__icontains=search)

    posts = (
        Post.objects.filter(q_obj)
        .select_related("category")
        .prefetch_related("tags")
        .order_by("-created_at")
    )

    paginator = Paginator(posts, 3)
    page_num = request.GET.get("page", 1)
    paginator = paginator.get_page(page_num)

    context = {
        "posts": paginator,
        "posts_count": posts.count(),
        "form": forms,
    }
    return render(request, "python_blog/blog.html", context=context)


def post_detail(request, post_slug):
    post = get_object_or_404(Post, slug=post_slug)

    session = request.session
    session_key = f"post_views_{post.id}"
    if session_key not in session:
        post.views = F("views") + 1
        post.save()
        post.refresh_from_db()
        session[session_key] = True

    context = {"post": post}
    return render(request, "python_blog/post_detail.html", context=context)


def catalog_categories(request):
    categories = Category.objects.all()
    categories_count = {cat.name: cat.posts.count() for cat in categories}
    context = {"categories": categories, "categories_count": categories_count}
    return render(request, "python_blog/catalog_categories.html", context=context)


def category_detail(request, category_slug):
    category = Category.objects.get(slug=category_slug)

    posts = (
        Post.objects.filter(category=category)
        .select_for_update("category")
        .prefetch_related("tags")
    )
    paginator = Paginator(posts, 3)
    page_num = request.GET.get("page", 1)
    paginator = paginator.get_page(page_num)

    context = {"category": category, "posts": paginator}

    return render(request, "python_blog/category_detail.html", context=context)


def catalog_tags(request):
    tags = Tag.objects.all()
    context = {"tags": tags}
    return render(request, "python_blog/tags_catalog.html", context=context)


def tag_detail(request, tag_slug):
    tag = Tag.objects.get(slug=tag_slug)

    context = {"tag": tag}
    return render(request, "python_blog/tag_detail.html", context=context)


def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()

            tags = form.cleaned_data.get("tag_string", "")
            if tags:
                tag_names = [t.strip() for t in tags.split(",")]
                for tag_name in tag_names:
                    if tag_name:
                        tag, created = Tag.objects.get_or_create(
                            name=tag_name,
                            defaults={"slug": slugify(unidecode(tag_name))},
                        )
                        post.tags.add(tag)

            return redirect(post.get_absolute_url())
        context = {
            "title": "Создание поста",
            "name": "Создание поста",
            "form": form,
            "url_to": reverse(
                "blog:post_create",
            ),
            "category": Category.objects.all(),
            "name_form": "Создание поста",
            "button_name": "Создать",
        }
        return render(request, "python_blog/post_create.html", context=context)
    else:
        form = PostForm()
        context = {
            "title": "Создание поста",
            "name": "Создание поста",
            "form": form,
            "category": Category.objects.all(),
            "name_form": "Создание поста",
            "button_name": "Создать",
        }
        return render(request, "python_blog/post_create.html", context=context)

def post_update(request, post_slug):
    post = get_object_or_404(Post, slug=post_slug)
    if request.method == "POST":
        old_slug = post.slug
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.slug = old_slug
            post.save()

            tag_string  = form.cleaned_data.get("tag_string", "")
            if tag_string :
                post.tags.clear()
                tag_names = [t.strip() for t in tag_string .split(",")]
                for tag_name in tag_names:
                    if tag_name:
                        tag, created = Tag.objects.get_or_create(
                            name=tag_name,
                            defaults={"slug": slugify(unidecode(tag_name))},
                        )
                        post.tags.add(tag)

            return redirect(post.get_absolute_url())
    else:
        form = PostForm(instance=post)
        context = {
            "title": "Редактирование поста",
            "name": "Редактирование поста",
            "form": form,
            "category": Category.objects.all(),
            "url_to": reverse("blog:post_update", kwargs={"post_slug": post.slug}),
            "name_form": "Редактирование поста",
            "button_name": "Сохранить",
        }
        return render(request, "python_blog/post_create.html", context=context)

blog/python_blog/templates/python_blog/blog.html
{% extends "base.html" %}

{% block title %}
Список всех постов
{% endblock %}

{% block content %}
<p>
    <a class="btn btn-primary" href="{% url "blog:post_create" %}">Создать пост</a>
</p>
<form action="{% url "blog:posts" %}" method="GET" class="row mb-3 border border-2 border-warning rounded-3 py-3 bg-warning-subtle">
    <div class="col-5 d-flex justify-content-between align-items-center">
        <div class="text-center fw-bold">
            <input type="radio" name="s_from" id="s_from_1" value="title" class="form-check-input" {% if form.s_from.value == "title" %}checked{% endif %}>
            <label for="s_from_1">Поиск по заголовкам</label>
        </div>

        <div class="text-center fw-bold">
            <input type="radio" name="s_from" id="s_from_2" value="content" class="form-check-input" {% if form.s_from.value == "content" %}checked{% endif %}>
            <label for="s_from_2">Поиск по тексту</label>
        </div>

        <div class="text-center fw-bold">
            <input type="radio" name="s_from" id="s_from_3" value="tags" class="form-check-input" {% if form.s_from.value == "tags" %}checked{% endif %}>
            <label for="s_from_3">Поиск по тегам</label>
        </div>
    </div>

    <div class="col-7 d-flex">
        <label for=""></label>
        <input type="text" name="search" placeholder="{% if form.search.value %}{{ form.search.value }} {% else %} Введите поисковый запрос...{% endif %}" class="form-control">
        <input type="submit" value="Найти" class="btn btn-primary">
    </div>
</form>

<div class="row">
    <div class="col-12">
        {% for post in posts %}
        {% include 'python_blog/post_preview_include.html' %}
        {% empty %}
        <div class="alert alert-info">
            <i>Посты не найдены</i>
        </div>
        {% endfor %}
    </div>
    {% include "python_blog/include_paginator.html" %}
</div>
{% endblock %}

blog/python_blog/templates/python_blog/catalog_categories.html
{% extends "base.html" %}
{% load mytags %}
{% block content %}

<h1>Список категорий</h1>
<hr>
{% for category in categories %}
<p>Категория: {{ category.name }}</p>
<a href="{% url 'blog:category_detail' category.slug %}">{{ category.name }}</a>
<p>Количество постов: {{categories_count|get_item:category.name}}
<hr>
{% endfor %}
{% endblock %}

blog/python_blog/templates/python_blog/category_detail.html
{% extends "base.html" %}
{% block content %}
<h1>Категория: {{category.name}}</h1>
<p>Список постов этой категории:</p>
<div class='row'>
    <div class="col">
        {% for post in posts %}
            {% include "python_blog/post_preview_include.html" %}
        {% endfor %}
    </div>
    {% include "python_blog/include_paginator.html" %}
</div>
{% endblock content %}

blog/python_blog/templates/python_blog/include_paginator.html
{% load mytags %}
{% if posts.paginator.num_pages > 1 %}
    <div class="row">
        <div class="col d-flex justify-content-center">
            {% for num in posts.paginator.num_pages|range_filter  %}
                <a href="?page={{ num|add:1 }}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}{% if request.GET.s_from %}&s_from={{request.GET.s_from}}{% endif %}" class="btn {% if posts.number|add:-1 == num %}btn-danger {% else %} btn-secondary {% endif %}  mx-2 mb-5">{{ num|add:1 }}</a>
            {% endfor %}
        </div>
    </div>
{% endif %}

blog/python_blog/templates/python_blog/menu_include.html
<nav>
    <ul>
        {% for item in menu_items %}
            <li>
                <a href="{% url item.url_name %}" 
                   class="{% if item.is_active %}active{% endif %}">
                    {{ item.title }}
                </a>
            </li>
        {% endfor %}
    </ul>
</nav>

blog/python_blog/templates/python_blog/post_create.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ name_form }}</h1>
    <form action="{{ url_to }}" method="POST" class="form-control">
        {% csrf_token %}
        <div class="fw-bold mb-3">
            <label for="id_title" class="form-label">Название статьи:</label>
            <input type="text" id="id_title" name="title" class="form-control" placeholder="{% if form.instance.title %} form.instance.title {% else %}Название статьи: {% endif %}" required value="{{ form.instance.title|default:"" }}">
        </div>

        <div class="fw-bold mb-3">
            <label for="id_content" class="form-label">Текст статьи:</label>
            <textarea id="id_content" name="content" class="form-control" placeholder="Текст статьи" required>{{ form.instance.content|default:"" }}</textarea>
        </div>  

        <div class="fw-bold mb-3">   
            <label for="" class="form-label">Выберите категорию:</label>
            {{ form.category }}
        </div> 

        <div class="fw-bold mb-3">
            <label for="id_tags" class="form-label">Теги статьи (через запятую):</label>
            <input type="text" id="id_tags" name="tag_string" placeholder="Теги статьи" class="form-control" 
                   value="{% if form.instance.id %}{% for tag in form.instance.tags.all %}{{ tag.name }}{% if not forloop.last %}, {% endif %}{% endfor %}{% endif %}">
        </div>
        

        <div class="">
            {% if form.errors %}
                <div class="error">
                    <strong>Ошибки:</strong>
                    <ul>
                        {% for field in form %}
                            {% for error in field.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <button type="submit" class="btn btn-primary">{{ button_name }}</button>
    </form>
{% endblock content %}

blog/python_blog/templates/python_blog/post_detail.html
{% extends "base.html" %}

{% block title %}
{{ post.title }}
{% endblock %}

{% block content %}
<div class="container mt-4">
    <!-- Заголовок и теги -->
    <div class="row mb-4">
        <div class="col-12">
            <h1>{{ post.title }}</h1>
            <div class="mb-3">
                {% for tag in post.hashtags %}
                    <span class="badge bg-primary me-1">#{{ tag }}</span>
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- Контент поста -->
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <span>Теги: </span>
                    {% if post.tags %}                
                    {% for tag in post.tags.all %}
                        <a href="{% url "blog:tags" %}{{tag.slug}}" class="btn btn-warning py-0 px-2 fst-italic">{{ tag.name }}</a>
                    {% endfor %}
                    {% else %}
                    <span>Нет тегов</span>
                    {% endif %}
                    <hr>
                    <p>Просмотров: {{ post.views}}</p>
                    <p class="card-text">{{ post.content }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    

    <!-- Кнопка возврата -->
    <div class="row mt-4">
        <div class="col-12">
            <a href="{% url "blog:post_update" post.slug %}" class="btn btn-danger my-3 float-end">Изменить</a>
            <a href="{% url 'blog:posts' %}" class="btn btn-outline-primary">
                <i class="bi bi-arrow-left"></i> Вернуться к списку постов
            </a>
        </div>
    </div>
</div>
{% endblock %}

blog/python_blog/templates/python_blog/post_preview_include.html
<div class="card mb-4">
    <div class="card-body">
        <a href="{{ post.get_absolute_url }}"><h2 class="card-title">{{ post.title }}</h2></a>
        <p class="card-text">{{ post.post|truncatewords:30 }}</p>
        <hr>
        <span>Теги: </span>
            {% if post.tags %}                
            {% for tag in post.tags.all %}
                <a href="{% url "blog:tags" %}{{tag.slug}}" class="btn btn-warning py-0 px-2 fst-italic">{{ tag.name }}</a>
            {% endfor %}
            {% else %}
            <span>Нет тегов</span>
            {% endif %}
            <hr>
        <span>Категория: </span>
            {% if post.category %}
                <a href="{% url "blog:category_detail" post.category.slug %}">{{post.category.name}}</a>
            {% endif %}
        <div class="d-flex justify-content-between align-items-center">
        </div>
    </div>
</div>

blog/python_blog/templates/python_blog/tag_detail.html
{% extends "base.html" %}
{% block content %}
<h1>Тег: {{tag.name}}</h1>
<p>Список постов с этим тегом</p>
<div class='row'>
    <div class="col">
        {% for post in tag.posts.all %}
            {% include "python_blog/post_preview_include.html" %}
        {% endfor %}
    </div>
</div>
{% endblock content %}

blog/python_blog/templates/python_blog/tags_catalog.html
{% extends "base.html" %}
{% block content %}

<h1>Список тегов</h1>
<hr>
{% for tag in tags %}
<a href="{% url "blog:tags" %}{{tag.slug}}" class="btn btn-warning py-0 px-2 fst-italic mb-2">{{ tag.name }}</a>
{% endfor %}
{% endblock %}